name: Fork, Patch, Build, and Push Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs daily; adjust as needed

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: whisparr-custom
  PATCH_REPO: teemosyndra/whisparr-patch
  PATCH_BRANCH: master # change if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout eros branch from upstream
        uses: actions/checkout@v4
        with:
          repository: whisparr/whisparr
          ref: eros
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
          fetch-tags: false

      - name: Checkout patch repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PATCH_REPO }}
          path: patch
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.PATCH_BRANCH }}

      - name: Apply patch
        run: |
          if compgen -G "patch/*.patch" > /dev/null; then
            for p in patch/*.patch; do
              git apply "$p"
            done
          else
            echo "No patch files found!"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Logout from Docker registries
        run: |
          docker logout
          docker logout ghcr.io
